LESSONS[3] = {
  goals: ["Define risk properly, and tell 'bumpy' from 'permanent loss'", "Use the recovery math that shows why big losses are so damaging", "Understand exactly how diversification protects you (and where it fails)", "Match your investments to your time horizon and your own tolerance"],
  body: [
    ["story", "The most expensive mistake", `Enron was one of America's biggest companies. Many of its employees kept their whole retirement savings in Enron stock, because they worked there and believed in it. In 2001 the company collapsed in an accounting scandal, and the stock went from about $90 to almost nothing. Employees lost their jobs <i>and</i> their savings at the same moment. It's the classic lesson: putting everything in one basket is a risk you are not paid to take.`],
    ["h", "1. What is risk, really?"],
    ["p", `In finance, people use 'risk' for two different things, and the difference matters:`],
    ["list", [`<b>Volatility</b>: how much prices bounce around. Bumpy but recoverable. A broad stock fund that drops 20% and later recovers was volatile, but you lost nothing permanent unless you sold.`, `<b>Permanent loss</b>: money that never comes back: a company that goes bankrupt, a scam, or you selling at the bottom in panic (or having to sell because you need the cash).`]],
    ["p", `Good investing means accepting some volatility (that's what pays you) while working hard to avoid permanent loss.`],
    ["h", "2. The math that makes losses hurt"],
    ["p", `Losses and gains are not symmetric. If you lose 50%, a 50% gain does <i>not</i> bring you back. From $100 down to $50, you need to <b>double</b> (+100%) to get back to $100.`],
    ["table", ["If you lose…", "You need to gain…", "To break even"], [["10%", "+11%", "Easy"], ["20%", "+25%", "A normal bear market"], ["33%", "+50%", "Painful"], ["50%", "+100%", "Years of recovery"], ["75%", "+300%", "Devastating"], ["90%", "+900%", "Practically wipes you out"]]],
    ["c", `<b>Takeaway:</b> avoiding the very big losses matters more than chasing the very big wins. That's the whole logic of diversification.`],
    ["h", "3. Two kinds of risk"],
    ["list", [`<b>Company-specific risk</b>: one firm's scandal, failed product or bankruptcy. You can nearly eliminate this by owning many companies.`, `<b>Market risk</b>: everything falls together (a recession, a financial crisis, a pandemic). You can't diversify this away within stocks; you only manage it with your mix of investments and your time horizon.`]],
    ["h", "4. Diversification: how it works"],
    ["p", `If you own one stock and it drops 60%, your portfolio drops 60%. If you own 500 stocks equally and one drops 60%, your portfolio drops 0.12%. One disaster gets diluted by 499 companies that are fine. Owning different <i>types</i> of companies (tech, health care, energy, banks, consumer goods) and different <i>regions</i> spreads it further.`],
    ["table", ["Portfolio", "If one holding falls 60%", "Damage"], [["1 stock", "100% of your money hit", "-60%"], ["10 stocks (equal)", "10% of your money hit", "-6%"], ["500 stocks (equal)", "0.2% of your money hit", "-0.12%"]]],
    ["h", "5. Where diversification fails"],
    ["p", `In a real crisis, most stocks fall together because investors sell everything, so 'correlations' rise. In 2008 the S&P 500 lost about 57% from its 2007 peak to March 2009, and almost every sector fell. What helped in 2008? Holding some <b>high-quality bonds</b> and <b>cash</b>, which fell much less and gave people something to rebalance with.`],
    ["h", "6. The main tool: asset allocation"],
    ["p", `How you split money between stocks, bonds and cash matters more than which stocks you choose. A rough picture:`],
    ["table", ["Mix", "Typical behaviour", "Worst-year feel (rough)"], [["100% stocks", "Highest long-run growth, biggest swings", "-35% to -50% in bad crashes"], ["70% stocks / 30% bonds", "Slightly calmer", "Roughly -25% to -35%"], ["40% stocks / 60% bonds", "Much calmer, lower growth", "Roughly -15% to -20%"]]],
    ["p", `Numbers are rough and vary by era. The point: <b>less stock = smaller crashes and smaller long-run growth</b>. There is no free lunch, only a choice.`],
    ["h", "7. Time horizon: the risk dial you control"],
    ["p", `History shows that the longer you hold a diversified stock fund, the less likely you are to lose money. Over any single year, US stocks lost money in roughly one year out of four; over any 20-year stretch, a broad US stock index has rarely lost money in the past. But 'rarely' isn't 'never', and history isn't a guarantee.`],
    ["list", [`<b>Money needed in under 5 years</b> (a car, college fees, a deposit): stocks are a poor fit. Keep it in savings-type accounts.`, `<b>5–10 years:</b> a mix of stocks and safer assets.`, `<b>10+ years</b> (retirement, wealth building): stocks can be the main engine, if you can stomach the drops.`]],
    ["h", "8. Your tolerance vs your capacity"],
    ["p", `<b>Risk capacity</b> is how much loss you could afford (a long time horizon and a stable income give you more). <b>Risk tolerance</b> is how much you can emotionally handle without panic-selling. Both matter. Someone who says 'I can handle a 50% drop' and then sells during a 25% drop has less tolerance than they thought. Real crashes are far scarier than hypothetical ones.`],
    ["mistake", [`<b>Owning 'diversified' picks that are really the same bet</b> (five different AI stocks are one AI bet).`, `<b>Loading up on your employer's stock</b>, so your job and savings share the same fate.`, `<b>Selling after a crash</b>, turning a temporary drop into a permanent loss.`, `<b>Overestimating your tolerance</b> in calm markets.`]],
    ["try", `Take a real or imaginary $1,000. Write down how you'd feel if it became $750 in three months (a 25% drop). Would you sell? Add more? Freeze? Your honest answer tells you more about your right mix of stocks and safer assets than any quiz. You'll use it in Lesson 8's plan builder.`],
    ["take", [`Risk = volatility (bumpy but recoverable) <i>and</i> permanent loss. Fight the second.`, `A 50% loss needs a 100% gain: avoid huge losses.`, `Diversification removes company-specific risk but not market risk.`, `Your <b>time horizon</b> and <b>honest tolerance</b> decide how much of your money belongs in stocks.`]]
  ],
  quiz: [
    { q: "Your $1,000 investment falls 50%. What gain do you need to get back to $1,000?", o: ["+50%", "+100%", "+150%"], a: 1, why: "$500 has to double to reach $1,000. Big losses are much harder to recover from than their size suggests." },
    { q: "Which risk can diversification reduce the MOST?", o: ["A recession hitting all companies", "One company going bankrupt", "Interest rates rising"], a: 1, why: "Owning many companies dilutes any single company's failure. Market-wide risk remains." },
    { q: "Someone holds 8 different AI chip and AI software stocks and calls it diversified. What is the issue?", o: ["Nothing, 8 is plenty", "They're all exposed to the same theme, so it's still one big bet", "Chip stocks can't fall"], a: 1, why: "Different tickers with the same driver tend to fall together." },
    { q: "You will need money for college fees in 2 years. Which fits best?", o: ["All in a single hot stock", "Mostly in stock funds", "Mostly in savings-type, low-risk accounts"], a: 2, why: "Short time horizons can't ride out a 30% drop that may take years to recover." },
    { q: "In a market crash you panic and sell everything at a 30% loss. What did you turn a temporary drop into?", o: ["A permanent loss", "A tax benefit only", "A safer investment"], a: 0, why: "Selling locks in the loss. Recoveries only help those who are still invested." }]
};
