LESSONS[5] = {
  goals: ["Read a price chart without being fooled by the timeframe", "Use moving averages and see what they do (and don't) tell you", "Understand valuation basics: P/E and earnings", "Test an investing 'rule' against history before trusting it"],
  body: [
    ["story", "Same chart, two opposite stories", `Two friends look at the same stock. Ana zooms in on the last two weeks: it fell 12%, 'it's crashing!'. Ben zooms out to five years: it's up 180%, 'it's a rocket!'. Both are reading the same data. <b>The timeframe you choose decides the story you see.</b> Learning to zoom in and out on purpose is the first skill of chart reading.`],
    ["h", "1. What a chart shows"],
    ["p", `A price chart plots price over time. A <b>line chart</b> connects closing prices, and is the cleanest way to see the trend. A <b>candlestick chart</b> shows four numbers per period (open, high, low, close) as a 'candle', useful for seeing the daily range. Below it, <b>volume</b> bars show how many shares traded: big moves on high volume mean more people agree.`],
    ["h", "2. Trends, support and resistance"],
    ["list", [`<b>Uptrend:</b> a series of higher highs and higher lows. <b>Downtrend:</b> lower highs and lower lows. <b>Sideways:</b> neither.`, `<b>Support:</b> a price area where buyers have repeatedly stepped in. <b>Resistance:</b> where sellers have repeatedly appeared.`, `Use these as <i>ideas</i>, not laws. Prices break support and resistance all the time.`]],
    ["h", "3. Moving averages: filtering the noise"],
    ["p", `A <b>moving average</b> (MA) is the average closing price over the last N days, recalculated every day. It smooths out day-to-day jumps and shows the underlying trend. Two are famous: the <b>50-day</b> (about 2.5 months) and the <b>200-day</b> (about 10 months). Here's the real thing, updated daily:`],
    ["chart"],
    ["p", `How people use them: price above the 200-day average is usually called a healthy long-term trend; price below it, a weak one. When the 50-day crosses above the 200-day it's called a 'golden cross', and below it a 'death cross'. Sounds dramatic, but be careful: moving averages are <b>lagging</b>. They tell you what already happened. By the time a death cross appears, prices have often already dropped a lot, and the market frequently bounces back afterward.`],
    ["c", `<b>Honest note:</b> in our own backtest of AI &amp; Tech Watch (1999–2026), 'price below its 50-day average' showed up mostly <i>after</i> drops had started: useful for confirming a downturn, weak at warning about one.`],
    ["h", "4. Valuation: is the price high relative to what the business earns?"],
    ["p", `Charts show price, but not whether the price is sensible. The most common yardstick is the <b>P/E ratio</b> (price ÷ earnings per share). Rough context for large US stocks: a P/E in the mid-teens has been about average for the broad market over history, mid-20s and up is expensive, and tech stocks at the height of the 2000 bubble often traded at P/Es of 100 or more.`],
    ["list", [`<b>Trailing P/E</b> uses the last 12 months of actual profits. <b>Forward P/E</b> uses analysts' guesses for the next 12 months (guesses can be wrong).`, `A high P/E can be justified if profits grow quickly; a low P/E can be a trap if profits are about to collapse.`, `Compare P/Es <i>within the same industry</i>, and against the company's own history.`]],
    ["h", "5. Other numbers worth a glance"],
    ["table", ["Metric", "What it tells you"], [["Revenue growth", "Is the business getting bigger?"], ["Profit margin", "How many cents of profit per dollar of sales?"], ["Debt", "Can it survive a bad year without borrowing more?"], ["Free cash flow", "Real cash left after running the business"]]],
    ["h", "6. What charts cannot do"],
    ["p", `Human brains see patterns even in random noise. Studies of chart-pattern trading (head-and-shoulders, triangles and so on) show little reliable edge after costs. Charts can't see the future, earnings surprises, wars, or new laws. Use them to <b>understand context</b>, not to predict.`],
    ["h", "7. The most valuable skill: testing an idea before trusting it"],
    ["p", `When we built AI &amp; Tech Watch, we started with two 'obvious' beliefs: <b>(1)</b> a very low VIX (calm markets) is a warning that complacency will end in a crash, and <b>(2)</b> a market far above its 200-day average is due for a fall. We tested both on 27 years of data. Both were wrong for short-term crashes: low-VIX periods were followed by <i>fewer</i> big drops, and stretched markets often kept rising. We dropped one and downgraded the other.`],
    ["c", `<b>This is the skill to steal:</b> before you trust any rule (yours, a friend's, an influencer's), ask "how would this have done in the past, including bad periods?" and "am I only remembering the times it worked?"`],
    ["mistake", [`<b>Reading only one timeframe.</b> Always zoom out.`, `<b>Treating patterns as certainties.</b> They're odds at best.`, `<b>Looking at price but not valuation or profits.</b>`, `<b>Cherry-picking</b> the examples that support your view (see confirmation bias in Lesson 7).`, `<b>Buying only because a stock 'crossed' a line</b> without any other reason.`]],
    ["try", `Pull up any stock or fund chart. View it at 1 month, 1 year and 5 years. Write one sentence for each timeframe about what story it tells. Then add the 50- and 200-day averages and note whether price is above or below each. Notice how the 'story' changes with the zoom level.`],
    ["take", [`Your <b>timeframe</b> shapes the story: always zoom out.`, `Moving averages smooth trends but <b>lag</b>; they confirm more than they predict.`, `Combine price with <b>valuation and profits</b>, not price alone.`, `<b>Test beliefs against history</b> before you trust them.`]]
  ],
  quiz: [
    { q: "A stock is down 10% this month but up 150% over five years. Which statement is most accurate?", o: ["It is crashing", "Both are true; the timeframe changes the story", "The 5-year view is wrong"], a: 1, why: "Different windows describe different things. Good analysis looks at several." },
    { q: "The 50-day moving average crosses below the 200-day (a 'death cross'). What is the best interpretation?", o: ["A guaranteed crash is coming", "A lagging signal that the trend has already weakened; not a prediction", "A signal to buy immediately"], a: 1, why: "Moving averages lag. They confirm what has happened; they don't reliably predict what's next." },
    { q: "Stock A has a P/E of 12. Stock B has a P/E of 60. Which conclusion is safest?", o: ["A is definitely the better investment", "B is definitely overpriced", "It depends on growth, industry and risks; P/E alone can't tell you"], a: 2, why: "P/E is a starting point. Fast-growing companies can justify higher P/Es; cheap ones can be traps." },
    { q: "Our backtest found that a very low VIX preceded FEWER large stock drops. What does this teach?", o: ["Intuitive rules should be tested; some are backwards", "Calm markets always continue", "Backtests are useless"], a: 0, why: "The lesson is to test, not to swap one belief for its opposite." },
    { q: "Why are moving averages called 'lagging'?", o: ["They're calculated from past prices, so they react after moves happen", "They're always wrong", "They only work on Fridays"], a: 0, why: "An average of past prices necessarily trails the current price." }]
};
