LESSONS[6] = {
  goals: ["Describe the five stages of a bubble and spot them in real history", "Know the size and duration of the major crashes (1929, 2000, 2008, 2020, 2022)", "Judge honestly whether today's AI boom has bubble features, and why nobody can time it", "Have a crash playbook: what to do, and what not to do"],
  body: [
    ["story", "Pets.com and the sock puppet", `In February 2000, an online pet-supply store called Pets.com went public, raising about $80 million. It had a sock-puppet mascot, a Super Bowl ad, and a business that lost money on almost every order it shipped. Nine months later, in November 2000, the company was shut down. That same year, the Nasdaq peaked and then fell about 78% over the next two and a half years. It took roughly 15 years for the Nasdaq Composite to get back to its 2000 high.`],
    ["h", "1. What is a bubble?"],
    ["p", `A <b>bubble</b> is when prices rise far above what the underlying assets can reasonably earn, driven by hype and the fear of missing out rather than by fundamentals. The tricky part: real technologies and real companies can still be in bubbles. The internet <i>was</i> world-changing, and internet stocks in 1999 were <i>still</i> wildly overpriced. Both are true.`],
    ["h", "2. The five stages (the Minsky-Kindleberger model)"],
    ["steps", [`<b>Displacement:</b> a real new thing appears (the web, cheap credit, AI chatbots) and changes expectations.`, `<b>Boom:</b> prices rise, early winners get attention, money flows in.`, `<b>Euphoria:</b> everyone is talking about it. 'This time is different.' Valuations stop mattering, and newcomers pile in, often using borrowed money.`, `<b>Profit-taking:</b> smart or nervous money starts selling, insiders sell, the market becomes jumpy.`, `<b>Panic:</b> prices fall faster than they rose, leverage forces selling, and confidence collapses.`]],
    ["h", "3. The big ones, by the numbers"],
    ["table", ["Event", "Drop (peak to low)", "How fast / how long", "What set it off"], [["1929–32 Great Crash", "Dow about -89%", "About 3 years; took until 1954 to regain the high", "Speculation on borrowed money, then bank failures"], ["2000–02 Dot-com", "Nasdaq about -78%", "About 2.5 years; ~15 years to regain", "Overhyped internet firms with no profits"], ["2007–09 Financial crisis", "S&amp;P 500 about -57%", "About 17 months", "Housing and debt collapse"], ["2020 COVID", "S&amp;P 500 about -34%", "33 days: the fastest bear market on record", "Pandemic shutdowns"], ["2022 Rate shock", "S&amp;P 500 about -25%; Nasdaq-100 about -35%", "About 9–10 months", "Inflation and fast rate hikes"]]],
    ["c", `<b>Notice:</b> crashes have very different causes, speeds, and recovery times. Some recovered in months (2020), some took 15+ years (Nasdaq 2000). That range is exactly why time horizon matters so much (Lesson 3).`],
    ["h", "4. Survivors and casualties"],
    ["p", `Not everything that falls in a crash is finished. Amazon's stock lost roughly 90% of its value after the dot-com peak, then went on to become one of the world's largest companies. But Pets.com and hundreds of others disappeared. Cisco was briefly the most valuable company in the world in March 2000, and then fell 80–90%. The lesson isn't 'never buy'; it's that paying any price for a good story is dangerous, and that diversification protects you from being wrong about which company survives.`],
    ["h", "5. Is there an AI bubble right now?"],
    ["p", `Honest answer: <b>nobody knows, and anyone who's certain is guessing.</b> Bubbles are only clearly visible in hindsight. What we can do is check for the classic features. Here's how our AI &amp; Tech Watch frames it, with today's live readings:`],
    ["snap"],
    ["table", ["Bubble feature", "What we check", "What to note"], [["Stretched valuations", "QQQ price-to-earnings", "High P/Es raise the stakes, but haven't timed crashes"], ["Concentration", "Cap-weighted vs equal-weighted Nasdaq-100", "A few giants carrying the market is a risk"], ["Spending vs earnings", "Big-4 tech capex growth vs revenue growth (SEC filings)", "Massive AI spending only pays off if revenue follows"], ["Euphoria/insiders", "Insider selling (SEC Form 4)", "Executives selling heavily can signal caution (or just routine planned sales)"], ["The trigger", "Chip stocks vs the market, trend, fear spike", "Our best-tested warning was chip stocks lagging"]]],
    ["c", `<b>What the backtest says:</b> our combined score made a 15%+ drop in the next 60 days about 1.7–2x as likely as normal. That's a modest tilt. Most warnings were <i>not</i> followed by a crash. Even at its best, no indicator times a top. Treat it as a weather report, not a fortune-teller.`],
    ["h", "6. The crash playbook"],
    ["p", `Decide what you'll do <b>before</b> a crash, when you're calm:`],
    ["list", [`<b>Keep a cash buffer</b> (3–6 months of expenses, in savings). Then a crash never forces you to sell stocks.`, `<b>Match risk to your horizon</b> (Lesson 3). Money needed soon is not in stocks.`, `<b>Diversify</b> beyond one theme. If AI is 80% of your portfolio, you're making a bet, not investing broadly.`, `<b>Rebalance</b> once a year: if stocks have soared, trim back to your planned mix. That systematically sells some highs.`, `<b>Don't panic sell.</b> Selling after a fall locks in the loss. In every past crash the people who stayed invested and kept buying regular amounts recovered.`, `<b>Don't try to time the top.</b> Sitting out for years while 'waiting for the crash' has cost many people more than the crash itself.`]],
    ["mistake", [`<b>"This time is different."</b> The technology may be; human behaviour isn't.`, `<b>Borrowing to invest</b> (margin). It turns dips into wipeouts.`, `<b>Selling everything on a scary headline</b>, then never getting back in.`, `<b>Betting everything on being right about the timing.</b>`]],
    ["try", `Open <a href='#/watch'>AI &amp; Tech Watch</a>. Which checks are flashing today? For each one that is, write one sentence: <i>what would have to happen for this to be a real problem, and what would make it a false alarm?</i> Then write your crash rule: "If markets fall 30%, I will…"`],
    ["take", [`Bubbles follow a pattern: displacement, boom, euphoria, profit-taking, panic.`, `Real technology can still be overpriced; great companies can still fall 80–90%.`, `Crashes range from 33 days (2020) to 15+ years of recovery (Nasdaq 2000).`, `No indicator times a top. Prepare with <b>a cash buffer, diversification, a long horizon and a written plan</b>.`]]
  ],
  quiz: [
    { q: "Which best describes the 'euphoria' stage of a bubble?", o: ["Prices are low and nobody is interested", "Everyone talks about it, valuations are ignored, newcomers borrow to buy", "Insiders quietly accumulate shares"], a: 1, why: "Euphoria is peak excitement and FOMO, usually with leverage, just before things turn." },
    { q: "Which crash was the fastest bear market on record?", o: ["2000 dot-com", "2008 financial crisis", "2020 COVID (about 33 days)"], a: 2, why: "The S&P 500 fell about 34% in just over a month in early 2020." },
    { q: "Amazon lost roughly 90% after the dot-com peak and then thrived; Pets.com disappeared. What's the main lesson?", o: ["Always buy after a crash", "You can't reliably know in advance which company survives, so diversify", "Technology stocks are always scams"], a: 1, why: "Being right about a technology isn't the same as picking the right company or price." },
    { q: "Our backtest found the combined AI &amp; Tech Watch score made a crash about 1.7–2x more likely. How should you treat a high score?", o: ["A guaranteed crash warning", "A modest tilt in probabilities; most warnings aren't followed by a crash", "Meaningless"], a: 1, why: "It's useful context and no more. Even with elevated odds, most periods don't end in crashes." },
    { q: "Which action best prepares you for a future crash?", o: ["Going all-in on the hottest theme before it drops", "Holding a cash buffer, diversifying, and having a written plan you follow", "Checking prices hourly"], a: 1, why: "Preparation, not prediction, is what protects you." }]
};
